#!/usr/bin/env python3
"""Refresh embedded Block Kit schemas from Slack's official Markdown feed."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import urllib.error
import urllib.request

SOURCE_URL = "https://docs.slack.dev/reference/block-kit.md"
SOURCE_PREFIX = "https://docs.slack.dev/reference/block-kit/"
REQUIRED_HEADINGS = ("## Blocks", "## Block elements", "## Composition objects")
DEFAULT_OUTPUT = pathlib.Path(
    "pkg/skill/slack-blockkit-ui/references/block-kit-reference.md"
)
SCHEMA_RESOURCE_PREFIX = "slack://skills/slack-blockkit-ui/schemas/"


class FetchError(RuntimeError):
    def __init__(self, url: str, status: int) -> None:
        super().__init__(f"failed to fetch {url}: HTTP {status}")
        self.url = url
        self.status = status


def fetch(url: str) -> str:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "slack-mcp-server-block-kit-reference-updater/1.0"},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            charset = response.headers.get_content_charset() or "utf-8"
            return response.read().decode(charset)
    except urllib.error.HTTPError as error:
        raise FetchError(url, error.code) from error


def schema_links(document: str) -> list[str]:
    return re.findall(r"\[[^]]+\]\((https://[^)]+)\)", document)


def validate(document: str) -> None:
    if not document.startswith("Source: https://docs.slack.dev/reference/block-kit"):
        raise ValueError("unexpected Block Kit reference source marker")
    for heading in REQUIRED_HEADINGS:
        if heading not in document:
            raise ValueError(f"missing required heading: {heading}")
    links = schema_links(document)
    if len(links) < 30:
        raise ValueError(f"expected at least 30 schema links, found {len(links)}")
    invalid = [link for link in links if not link.startswith(SOURCE_PREFIX)]
    if invalid:
        raise ValueError(f"unexpected schema link outside Slack docs: {invalid[0]}")


def schema_name(url: str) -> str:
    relative = url.removeprefix(SOURCE_PREFIX).removesuffix(".md")
    if not re.fullmatch(
        r"(blocks|block-elements|composition-objects)/[a-z0-9-]+", relative
    ):
        raise ValueError(f"unsupported Block Kit schema URL: {url}")
    return relative.replace("/", "--") + ".md"


def render_index(document: str) -> str:
    body = document.removeprefix(
        "Source: https://docs.slack.dev/reference/block-kit\n\n"
    ).strip()
    for link in schema_links(document):
        body = body.replace(link, SCHEMA_RESOURCE_PREFIX + schema_name(link))
    return (
        "<!-- Generated by scripts/update-block-kit-reference.py. Do not edit. -->\n"
        "# Current Slack Block Kit reference\n\n"
        f"Authoritative source: {SOURCE_URL.removesuffix('.md')}\n\n"
        "This index is refreshed from Slack's official documentation. Read each linked\n"
        "schema resource before using that component; field requirements, limits,\n"
        "compatible parents, and supported surfaces live in the linked resource.\n\n"
        + body.removeprefix("# Reference: Block Kit").strip()
        + "\n"
    )


def render_schema(url: str, document: str) -> str:
    expected_source = url.removesuffix(".md")
    if not document.startswith(f"Source: {expected_source}\n"):
        raise ValueError(f"unexpected source marker for {url}")
    schema = document.split("## Examples", 1)[0]
    schema = "\n".join(
        line.rstrip()
        for line in schema.splitlines()
        if not line.startswith("![") and line.strip() != "Example:"
    )
    # MCP resources have a slack:// base, so root-relative links must remain
    # navigable after the page is embedded.
    schema = re.sub(r"\]\(/([^)]*)\)", r"](https://docs.slack.dev/\1)", schema)
    return (
        "<!-- Generated by scripts/update-block-kit-reference.py. Do not edit. -->\n"
        + schema.strip()
        + "\n"
    )


def render_unavailable_schema(url: str) -> str:
    return (
        "<!-- Generated by scripts/update-block-kit-reference.py. Do not edit. -->\n"
        "# Official Slack schema page unavailable\n\n"
        f"Source: {url.removesuffix('.md')}\n\n"
        "Slack lists this schema in the Block Kit reference, but its official Markdown\n"
        "endpoint currently returns HTTP 404. Do not infer its fields. Re-run the\n"
        "updater or consult the source URL before using this object.\n"
    )


def expected_files(document: str, output: pathlib.Path) -> dict[pathlib.Path, str]:
    files = {output: render_index(document)}
    schema_dir = output.parent / "schemas"
    for url in schema_links(document):
        try:
            content = render_schema(url, fetch(url))
        except FetchError as error:
            if error.status != 404:
                raise
            content = render_unavailable_schema(url)
        files[schema_dir / schema_name(url)] = content
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=SOURCE_URL)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    document = fetch(args.source)
    validate(document)
    files = expected_files(document, args.output)

    if args.check:
        stale = [
            path
            for path, content in files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        extras = sorted((args.output.parent / "schemas").glob("*.md"))
        extras = [path for path in extras if path not in files]
        for path in stale:
            print(f"{path} is out of date", file=sys.stderr)
        for path in extras:
            print(f"{path} is no longer in Slack's reference", file=sys.stderr)
        return 1 if stale or extras else 0

    schema_dir = args.output.parent / "schemas"
    schema_dir.mkdir(parents=True, exist_ok=True)
    for path in schema_dir.glob("*.md"):
        if path not in files:
            path.unlink()
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
